name: AICoverEnv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10  # Python versiyonunu belirleyin, bazı kütüphaneler belirli versiyonlarla daha uyumlu olabilir
  - pip
  - pip:
    - soundfile
    - pytube
    - pydub
    - noisereduce
    - librosa
    - pandas
    - google-api-python-client
    - ffmpeg  # pydub için gerekli
